---
- name: Create users with SSH keys and common group
  hosts: all
  become: yes
  vars:
    common_group: psup-re  # Имя общей группы
    sudoers_file: "/etc/sudoers.d/90-{{ common_group }}-nopasswd"  # Файл sudoers
    users:
      - name: alni0613
        ssh_key: "<SSH_key_alni0613>"
      - name: kiko0217
        ssh_key: "<SSH_key_kiko0217>"

  tasks:
    - name: Ensure common group exists
      ansible.builtin.group:
        name: "{{ common_group }}"
        state: present

    - name: Install sudo
      ansible.builtin.apt:
        name: sudo
        state: present

    - name: Ensure users exist with their home directories and in common group
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        create_home: yes
        home: "/home/{{ item.name }}"
        groups: "{{ common_group }}"
        append: yes  # Добавляем к существующим группам
      loop: "{{ users }}"

    - name: Ensure .ssh directory exists for each user
      ansible.builtin.file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Add SSH public key to authorized_keys for each user
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.ssh_key }}"
        state: present
        exclusive: yes
      loop: "{{ users }}"
      
    - name: Configure passwordless sudo for the common group
      ansible.builtin.copy:
        dest: "{{ sudoers_file }}"
        content: "%{{ common_group }} ALL=(ALL) NOPASSWD: ALL"
        owner: root
        group: root
        mode: '0740'

# По умолчанию не хватает модуля
# ansible-galaxy collection install ansible.posix
# или конкретную версию   ansible-galaxy collection install ansible.posix:1.4.0
